kind: PersistentVolume
apiVersion: v1
metadata:
  name: invoicexml-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/admin/volumes/xml/"
