apiVersion: v1
kind: Service
metadata:
  name: ck-invoicexml
  namespace: qa
  labels:
    app: ck-invoicexml
    version: 0.1.15
    environment: qa
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
    targetPort: portinvoicexml
  selector:
    app: ck-invoicexml
    version: 0.1.15
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
